### ISSUE TITLE
bei Bilder 

### ISSUE THREAD

**Issue by rwiebe** [youthweb/bbcode-parser#3]
Ich schreibe diesen Text in ein Textfeld:

[img]myserver.com/Pfad/zum/Bild.jpg[/img]
Was ich erhalte:

im text wird nur der Pfad angezeigt

Was ich erwarte:
dass das Bild im Text mit eingebunden wird

Schreibe ich aber
[img]http://myserver.com/Pfad/zum/Bild.jpg[/img]

erhalte ich die gewünschte Lösung

Der parser muss erkennen, ob ein http:// davor steht, wenn nicht vorhanden selber einfügen

**Comment by Art4** [comment]
Sobald Release 1.0 fertig ist, wird das auch auf Youthweb verwendet und dort gefixt sein. Danke für den Bug Report.
